---
title: "Summary table"
author: "Naser Ahmadi"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}

# Loading required packages
knitr::opts_chunk$set(include = FALSE)
library(tidyverse)
library(haven)
library(openxlsx)
library(srvyr)
library(survey)
library(knitr)
library(readr)
library(gdata)
library(ggplot2)
library(gridExtra)
library(maptools)
#library(gpclib)
library(grid)
library(RColorBrewer)
library(colorspace)
library(foreign)
library(rgdal)
library(readstata13)
library(grDevices)
library(png)
library(kutils)
library(labelled)
library(pdftools)
# Reading the Data
final.data <- read.xlsx("../Resources/data.xlsx")
#Creating new variables and labeling
varlabel <- read.xlsx("../Resources/codemap.xlsx")
for(i in varlabel$question_code[!is.na(varlabel$formula)]){
  j <- varlabel$new_var[varlabel$question_code == i]
  k <- varlabel$formula[varlabel$question_code == i]
  final.data <- final.data %>% mutate(!!j := as.numeric(eval(parse(text =  paste0(i ,k)))))
  
  var_label(final.data[[j]]) <- varlabel$new_label[varlabel$question_code==i]

}
# 
final.data <- final.data %>% mutate(Age=if_else(q1<=2,1,if_else(q1<=5,2,if_else(q1<=7,3,4))))
final.data$Age=labelled(as.factor(final.data$Age),c("12 years and younger"=1,"13 to 15"=2,"16 or 17"=3,"18 or older"=4))

final.data <- final.data %>% mutate(Age_1=if_else(q1<=2,1,if_else(q1<=7,2,3)))
final.data$Age_1=labelled(as.factor(final.data$Age_1),c("12 years and younger"=1,"13 to 17"=2,"18 or older"=4))

final.data$q2=labelled(as.factor(final.data$q2),c("Female"=2,"Male"=1))
final.data$q3=labelled(as.factor(final.data$q3),c("Octavo (8)"=1,"Noveno (9)"=2,"Primer Curso (1)"=3,"Segundo Curso (2)"=4,"Tercer Curso (3)"=5))

```


```{r q, echo=FALSE}
out = NULL
# vr="qn6"
try({for (vr in final.data %>% select(starts_with("qn")) %>% colnames()) {
      variable <- vr 
      desc1 <- var_label(final.data %>% select(vr))[[1]]
  out = c(out, knit_expand("../codes/Table T3_q.Rmd"))
  }
})

```
`r paste(knit(text = out), collapse = '\n')`


